# Generated by Django 5.2.17 on 2026-09-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Pilates', 'Pilates'), ('Bootcamp', 'Bootcamp'), ('Online', 'Online')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="e.g., 'home_hero_title'", max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_images/')),
                ('video_url', models.URLField(blank=True, help_text='Link to external video (e.g., YouTube)', null=True)),
            ],
        ),
    ]
