# Generated by Django 5.2.17 on 2026-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faqcategory_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Direct upload for image or video', null=True, upload_to='site_media/'),
        ),
    ]
